name: Build

on:
  push:
    branches:
      - "*"
  workflow_dispatch:
    

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6

      - name: Restore NuGet packages
        run: dotnet restore -p:Platform=Android

      - name: Build Debug
        run: dotnet build -c Debug -p:Platform=Android -p:DefineConstants=DEBUG%3bTRACE%3bANDROID --no-restore
      
      - name: Build Release
        run: dotnet build -c Release -p:Platform=Android -p:DefineConstants=RELEASE%3bTRACE%3bANDROID --no-restore

      - name: Upload mod dll
        uses: actions/upload-artifact@v4
        with:
          name: Submerged-Debug
          path: Submerged/bin/Android/Debug/net6.0/Submerged.dll

      - name: Upload mod dll (Release)
        uses: actions/upload-artifact@v4
        with:
          name: Submerged-Release
          path: Submerged/bin/Android/Release/net6.0/Submerged.dll
